boiler-plate:
  command-topics-in-master-index: false
  ignore-plugins: []
  amended-topics:
    Aliases:
      shortText: '&a<text>.&f'

style:
  quote: '&a&o'
  code: '&e&o'
  link: '&b'
  bold: '&e&l'
  strikethrough: '&m'
  underline: '&n'
  italics: '&o'
  headings:
  - '&c&o'
  - '&d&o'
  - '&a&o'
  - '&6&o'
  - '&d&o'

html:
  output-file: index.html
  default-topic-title: Topics
  visible-permissions:
  - ''
  - 'bukkit.command.help'
  header: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>${server} Help</title>
    <link rel="stylesheet" href="style.css">
    </head>
    <body>
    <h1>${server} Help</h1>
  footer: |
    </body>
    </html>
