name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
main: nu.nerd.help.HelpHelp
permissions:
  helphelp.dump:
    description: Permission to dump the help topics.
    default: op
  helphelp.reload:
    description: Permission to reload help topics and the configuration.
    default: op
  helphelp.load:
    description: Permission to load help topics from a remote Markdown file.
    default: op

commands:
  help-dump:
    description: Dump help to a file in the configuration directory.
    permission: helphelp.dump
    usage: |
    
      §e/<command> <url>§f - Dump help to a file in the configuration directory.

  help-reload:
    description: Reload the help topics and configuration from disk.
    permission: helphelp.reload
    usage: |
    
      §e/<command>§f - Reload the help topics and configuration from disk.

  help-load:
    description: Load help from the help file on disk.
    permission: helphelp.load
    usage: |
    
      §e/<command> <url>§f - Load help from a remote Markdown file.

