name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
main: nu.nerd.help.HelpHelp
permissions:
  helphelp.dump:
    description: Permission to use /help-dump.
    default: op
  helphelp.reload:
    description: Permission to use /help-reload.
    default: op
  helphelp.load:
    description: Permission to use /help-load.
    default: op

commands:
  help-dump:
    description: Dump help topics to a file in the configuration directory.
    permission: helphelp.dump
    usage: |
    
      §e/<command> <url>§f - Dump help topics to a file in the configuration directory.

  help-reload:
    description: Reload the help topics and configuration from disk.
    permission: helphelp.reload
    usage: |
    
      §e/<command>§f - Reload the help topics and configuration from disk.

  help-load:
    description: Load help from a remote Markdown file.
    permission: helphelp.load
    usage: |
    
      §e/<command> <url>§f - Load help from a remote Markdown file.

  help-url:
    description: Show the last URL loaded by §e/help-load§f.
    permission: helphelp.load
    usage: |
    
      §e/<command>§f - Show the last URL loaded by §e/help-load§f.
