name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
main: nu.nerd.help.HelpHelp
permissions:
  helphelp.admin:
    description: Permission to administer the plugin.
    default: op
  helphelp.faq:
    description: Permission to look up FAQs.
    default: op
commands:
  helphelp:
    description: Plugin administration command.
    permission: helphelp.admin
    usage: |
      /<command> reload: Reload the configuration.
      /<command> dump: Dump all help topics to a file in the plugin directory.
  faq:
    description: Answer Frequently-Asked Questions (FAQs).
    permission: helphelp.faq
    usage: |
      /<command> <word>: Search for topics relating to <word> in the FAQ section.

